# Use the official Nginx base image
FROM nginx:latest

# Copy custom configuration file to Nginx
COPY ./nginx.conf /etc/nginx/nginx.conf

# Copy your website content to the default directory
COPY ./html /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx service
CMD ["nginx", "-g", "daemon off;"]
